# Generated by Django 5.2.3 on 2025-06-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_created=True)),
                ("title", models.CharField(default="Untitled", max_length=100)),
                ("content", models.CharField(max_length=1000)),
                (
                    "mood",
                    models.CharField(
                        choices=[
                            ("Best", "best"),
                            ("Good", "good"),
                            ("Meh", "meh"),
                            ("Crappy", "crappy"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
