# Generated by Django 5.2.3 on 2025-06-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="user_id",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="journal",
            name="mood",
            field=models.CharField(
                choices=[
                    ("Happy", "happy"),
                    ("Fine", "fine"),
                    ("Groggy", "groggy"),
                    ("Crappy", "crappy"),
                ],
                max_length=20,
            ),
        ),
    ]
