# Generated by Django 5.2.3 on 2025-06-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0002_journal_user_id_alter_journal_mood"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journal",
            name="content",
            field=models.TextField(),
        ),
    ]
