# Generated by Django 5.2.3 on 2025-06-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="details",
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
